version: '3.8'

services:
  # 1. The Database
  db:
    image: mysql:8.0
    container_name: psydoc-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: psydoc_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # 2. The Go Backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: psydoc-backend
    restart: always
    ports:
      - "8080:8080"
      - "2345:2345" # FIXED: Added hash for comment
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: psydoc_db
    depends_on:
      - db
    volumes:
      - ./server:/app
      - ./server/uploads:/app/uploads

  # 3. The React Frontend
  frontend:
    build: ./client
    container_name: psydoc-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data: